branch-defaults:
  beanstalk:
    environment: Hamlet-Prod
environment-defaults:
  Hamlet-Prod:
    branch: null
    repository: null
global:
  application_name: hamlet
  default_ec2_keyname: mit-dornera
  default_platform: arn:aws:elasticbeanstalk:us-east-1::platform/Python 3.6 running
    on 64bit Amazon Linux/2.6.1
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
